/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FAkses;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class FRegister extends javax.swing.JFrame {

    /**
     * Creates new form FRegister
     */
    public FRegister() {
        initComponents();
        invi.setVisible(false);
        invi1.setVisible(false);
        
//    setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
//        setResizable(false);
    }

    public static boolean checkusername(String username) {
        try {
            // Koneksi ke database
            Connection conn = DriverManager.getConnection("jdbc:mysql://0.tcp.ap.ngrok.io:10827/db_uas_pbo2", "root", "");

            // Kueri untuk mencari email di database
            String query = "SELECT * FROM user WHERE username=?";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(2, username);
            ResultSet rs = stmt.executeQuery();

            // Jika email sudah ada di database, kembalikan true
            if (rs.next()) {
                return true;
            }

//            // Tutup koneksi dan statement
//            rs.close();
//            stmt.close();
//            conn.close();
        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }

        // Jika email tidak ada di database, kembalikan false
        return false;

    }

    public static String generateIDuser() {
    try (Connection conn = DriverManager.getConnection("jdbc:mysql://0.tcp.ap.ngrok.io:10827/db_uas_pbo2", "root", "")) {
        String id_user = null;
        int newId = 1;
        boolean idExists = true;

        while (idExists) {
            String idToCheck = String.format("USER%03d", newId);
            String checkIdQuery = "SELECT COUNT(*) AS count FROM user WHERE id_user = ?";
            PreparedStatement checkIdStatement = conn.prepareStatement(checkIdQuery);
            checkIdStatement.setString(1, idToCheck);
            ResultSet resultSet = checkIdStatement.executeQuery();

            int count = 0;
            if (resultSet.next()) {
                count = resultSet.getInt("count");
            }

            if (count == 0) {
                id_user = idToCheck;
                idExists = false;
            } else {
                newId++;
            }
        }

        return id_user;
    } catch (SQLException e) {
        e.printStackTrace();
    }
    return null;
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPasswordTextPlaceHolderBeanInfo1 = new rojerusan.RSPasswordTextPlaceHolderBeanInfo();
        jPanel1 = new javax.swing.JPanel();
        visi = new javax.swing.JLabel();
        invi = new javax.swing.JLabel();
        visi1 = new javax.swing.JLabel();
        invi1 = new javax.swing.JLabel();
        textpw = new rojerusan.RSPasswordTextPlaceHolder();
        back = new rojerusan.RSMaterialButtonRectangle();
        textpw2 = new rojerusan.RSPasswordTextPlaceHolder();
        btnsimpan = new rojerusan.RSMaterialButtonRectangle();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        visi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/invisible.png"))); // NOI18N
        visi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visiMouseClicked(evt);
            }
        });
        jPanel1.add(visi, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 20, 20));

        invi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/eye.png"))); // NOI18N
        invi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inviMouseClicked(evt);
            }
        });
        jPanel1.add(invi, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, -1, 20));

        visi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/invisible.png"))); // NOI18N
        visi1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visi1MouseClicked(evt);
            }
        });
        jPanel1.add(visi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, -1, 20));

        invi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/eye.png"))); // NOI18N
        invi1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invi1MouseClicked(evt);
            }
        });
        jPanel1.add(invi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, -1, 20));

        textpw.setForeground(new java.awt.Color(12, 31, 70));
        textpw.setPhColor(new java.awt.Color(12, 31, 70));
        textpw.setSelectionColor(new java.awt.Color(12, 31, 70));
        textpw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textpwActionPerformed(evt);
            }
        });
        jPanel1.add(textpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 230, 40));

        back.setBackground(new java.awt.Color(12, 31, 70));
        back.setBorder(null);
        back.setText("KEMBALI");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 230, 50));

        textpw2.setForeground(new java.awt.Color(12, 31, 70));
        textpw2.setPhColor(new java.awt.Color(12, 31, 70));
        textpw2.setSelectionColor(new java.awt.Color(12, 31, 70));
        textpw2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textpw2ActionPerformed(evt);
            }
        });
        jPanel1.add(textpw2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 230, 40));

        btnsimpan.setBackground(java.awt.SystemColor.textHighlight);
        btnsimpan.setText("simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 230, 50));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Confirm password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, -1, 20));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/close.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, -1, -1));

        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        jPanel1.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 230, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Register.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textpw2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textpw2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textpw2ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
      FAkses.FLogin mu = new FAkses.FLogin();
      mu.setVisible(true);
      dispose();
    }//GEN-LAST:event_backActionPerformed

    private void textpwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textpwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textpwActionPerformed

    private void inviMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inviMouseClicked
        // TODO add your handling code here:
        textpw.setEchoChar('*');
        invi.setVisible(false);
        visi.setVisible(true);
    }//GEN-LAST:event_inviMouseClicked

    private void visiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visiMouseClicked
        // TODO add your handling code here:
        textpw.setEchoChar((char) 0);

        visi.setVisible(false);
        invi.setVisible(true);
    }//GEN-LAST:event_visiMouseClicked

    private void visi1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visi1MouseClicked
        // TODO add your handling code here:
          textpw2.setEchoChar((char) 0);

        visi1.setVisible(false);
        invi1.setVisible(true);
    }//GEN-LAST:event_visi1MouseClicked

    private void invi1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invi1MouseClicked
        // TODO add your handling code here
          textpw2.setEchoChar('*');
        invi1.setVisible(false);
        visi1.setVisible(true);
    }//GEN-LAST:event_invi1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
            String username = txtuser.getText();
        String password = textpw.getText();
        String password2 = textpw2.getText();
        String level = "marketing";

        if (username.isEmpty() || password.isEmpty() || password2.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Semua teks wajib diisi");
        } else {
            if (password2.equals(password)) {
                if (checkusername(username)) {
                    JOptionPane.showMessageDialog(null, "Username sudah terdaftar");
                } else {
                    String id_user = generateIDuser();
                    try (Connection conn = DriverManager.getConnection("jdbc:mysql://0.tcp.ap.ngrok.io:10827/db_uas_pbo2", "root", "")) {
                        String sql = "INSERT INTO user ("
                                + "id_user, username, password, level) "
                                + "VALUES (?, ?, ?, ?)";

                        PreparedStatement statement = conn.prepareStatement(sql);
                        statement.setString(1, id_user);
                        statement.setString(2, username);
                        statement.setString(3, password);
                        statement.setString(4, level);

                        int rowsInserted = statement.executeUpdate();
                        if (rowsInserted > 0) {
                        JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                        }
                    } catch (SQLException e) {
                        e.printStackTrace();
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Confirm password tidak sama");
            }
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle back;
    private rojerusan.RSMaterialButtonRectangle btnsimpan;
    private javax.swing.JLabel invi;
    private javax.swing.JLabel invi1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private rojerusan.RSPasswordTextPlaceHolderBeanInfo rSPasswordTextPlaceHolderBeanInfo1;
    private rojerusan.RSPasswordTextPlaceHolder textpw;
    private rojerusan.RSPasswordTextPlaceHolder textpw2;
    private javax.swing.JTextField txtuser;
    private javax.swing.JLabel visi;
    private javax.swing.JLabel visi1;
    // End of variables declaration//GEN-END:variables
}
