/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package other;

import static Data.FGudang.textid;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class FdataDiizinkan extends javax.swing.JFrame {

    /**
     * Creates new form FdataDiizinkan
     */
    public FdataDiizinkan() {
        initComponents();
        tampil();
    }

    public void setTextId(String idgudang, String idpengelolaan) {
        Data.FGudang.textid.setText(idgudang);
        Data.FGudang.textidp.setText(idpengelolaan);

        dispose();
    }

//    public void delete(String kodeAlat) {
//        int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin Mengambil data ini?\njika ya maka akan terhapus otomatis", "Konfirmasi", JOptionPane.YES_NO_OPTION);
//        if (confirm == JOptionPane.YES_OPTION) {
//            try (Connection conn = Koneksi.KoneksiDatabase.getKoneksi()) {
//                String sql = "DELETE FROM tb_pengelolaan WHERE kode_alat = ?";
//                PreparedStatement statement = conn.prepareStatement(sql);
//                statement.setString(1, kodeAlat);
//
//                int rowsDeleted = statement.executeUpdate();
//                if (rowsDeleted > 0) {
//                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
//                } else {
//                    JOptionPane.showMessageDialog(null, "Tidak ada data yang terhapus");
//                }
//            } catch (SQLException e) {
//                e.printStackTrace();
//            }
//        }
//    }
    public void tampil() {
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://0.tcp.ap.ngrok.io:10827/db_uas_pbo2", "root", "")) {
            String sql = "SELECT * FROM tb_pengelolaan WHERE status = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, "diizinkan");
            ResultSet rs = stmt.executeQuery();

            // Menghapus data sebelumnya dari model tabel
            DefaultTableModel tableModel = (DefaultTableModel) tampill.getModel();
            tableModel.setRowCount(0);
            tableModel.setColumnCount(0);
            tableModel.addColumn("ID pengelolaan");
            tableModel.addColumn("ID gudang");
            tableModel.addColumn("Kode Alat");
            tableModel.addColumn("Nama Alat");
            tableModel.addColumn("Jumlah");
            tableModel.addColumn("Harga");
            tableModel.addColumn("Merek");
            tableModel.addColumn("Tanggal Masuk Gudang");
            tableModel.addColumn("Status");

            // Mengisi data ke model tabel
            while (rs.next()) {
                String idp = rs.getString("id_pengelolaan");
                String id = rs.getString("id_gudang");
                String kodeAlat = rs.getString("kode_alat");
                String namaAlat = rs.getString("nama_alat");
                int jumlah = rs.getInt("jumlah");
                int harga = rs.getInt("harga");
                String merek = rs.getString("merek");
                String tanggalMasuk = rs.getString("tglmskgudang");
                String status = rs.getString("status");
                Object[] rowData = {idp, id, kodeAlat, namaAlat, jumlah, harga, merek, tanggalMasuk, status};
                tableModel.addRow(rowData);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tampill = new rojerusan.RSTableMetro();
        rSMetroTextPlaceHolder1 = new rojerusan.RSMetroTextPlaceHolder();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/close.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, -1, 40));

        tampill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tampill.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tampill.setGridColor(new java.awt.Color(12, 31, 70));
        tampill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tampillMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tampill);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 670, 460));

        rSMetroTextPlaceHolder1.setForeground(new java.awt.Color(12, 31, 70));
        rSMetroTextPlaceHolder1.setText("SEARCH");
        rSMetroTextPlaceHolder1.setBorderColor(new java.awt.Color(12, 31, 70));
        rSMetroTextPlaceHolder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMetroTextPlaceHolder1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMetroTextPlaceHolder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tampillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tampillMouseClicked
        // TODO add your handling code here:
        int row = tampill.getSelectedRow();

// Mengambil data dari tabel
        int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin Mengambil data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            String idpengelolaan = tampill.getValueAt(row, 0).toString();
            String idgudang = tampill.getValueAt(row, 1).toString();
            String kodealat = tampill.getValueAt(row, 2).toString();
            String jmlh = tampill.getValueAt(row, 4).toString();
            String hargaStr = tampill.getValueAt(row, 5).toString();

            for (int i = 0; i < Data.FGudang.cbkode_alat.getItemCount(); i++) {
                if (Data.FGudang.cbkode_alat.getItemAt(i).toString().equals(kodealat)) {
                    Data.FGudang.cbkode_alat.setSelectedIndex(i);
                    break;
                }

            }

            Data.FGudang.textharga.setText(hargaStr);
            Data.FGudang.txtjumlah.setText(jmlh);
            Data.FGudang.txtjumlah.setEnabled(false);
            setTextId(idgudang, idpengelolaan);

            Data.FGudang.idpp.setVisible(true);
            textid.setVisible(false);
            Data.FGudang.textidp.setVisible(true);
            textid.setVisible(true);
            Data.FGudang.idgg.setVisible(true);
        }
// Mengisi data ke dalam form input
//        delete(kodealat);
    }//GEN-LAST:event_tampillMouseClicked

    private void rSMetroTextPlaceHolder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMetroTextPlaceHolder1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMetroTextPlaceHolder1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FdataDiizinkan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FdataDiizinkan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FdataDiizinkan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FdataDiizinkan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FdataDiizinkan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSMetroTextPlaceHolder rSMetroTextPlaceHolder1;
    public static rojerusan.RSTableMetro tampill;
    // End of variables declaration//GEN-END:variables
}
